import { Plugin, ResolvedConfig } from "vite";
import fs from "fs";
import path from "path";

type AgnosticViteOptions = {
    assetsDir: string;
};

export const agnosticVite = (opts: AgnosticViteOptions): Plugin => {
    let vite: ResolvedConfig;
    let runtimeContent = "";

    return {
        name: "agnostic-vite",

        configResolved(cfg) {
            vite = cfg;

            const isDevHelper = `
 const IS_DEV = ${vite.command === "serve"};

 const VITE_HOST = ${JSON.stringify(
                vite.server?.host
                    ? `http://${vite.server.host}:${vite.server.port}`
                    : "http://localhost:5173"
            )};
            
 const OUT_DIR = "${vite.build.outDir.split("/")[1] || vite.build.outDir}";
 
 const BASE_ASSETS_DIR = "public"
`;

            const manifestHelper = `
async function fetchText(file) {
    return await (await fetch(file)).text();
}

async function loadManifest() {
    const url = OUT_DIR + "/" + "manifest.json";
    return JSON.parse(await fetchText(url));
}

async function getAsset(entry) {
    const manifest = await loadManifest();
    return manifest[BASE_ASSETS_DIR + "/" + entry] || null;
}
`;

            const tagHelpers = `
async function jsTag(entry) {
    if (IS_DEV) {
        const script = document.createElement("script");
        script.type = "module";
        script.crossOrigin = true;
        script.src = VITE_HOST + "/" + entry;
        document.head.appendChild(script);
        return;
    }

    const asset = await getAsset(entry);
    if (!asset) return;

    const script = document.createElement("script");
    script.type = "module";
    script.src = OUT_DIR + "/" + asset.file;
    document.head.appendChild(script);

    if (asset.css) {
        asset.css.forEach(cssFile => {
            const link = document.createElement("link");
            link.rel = "stylesheet";
            link.href = OUT_DIR + "/" + cssFile;
            document.head.appendChild(link);
        });
    }
}

async function cssTag(entry) {
    if (IS_DEV) {
        const link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = VITE_HOST + "/" + entry;
        document.head.appendChild(link);
        return;
    }

    const asset = await getAsset(entry);
    if (!asset) return;

    if (asset.css) {
        asset.css.forEach(cssFile => {
            const link = document.createElement("link");
            link.rel = "stylesheet";
            link.href = OUT_DIR + "/" + cssFile;
            document.head.appendChild(link);
        });
    }
}

if (typeof window !== "undefined") {
    window.jsTag = jsTag;
    window.cssTag = cssTag;
}
`;

            runtimeContent =
                "// Auto-generated by agnostic-vite plugin\n\n" +
                isDevHelper +
                manifestHelper +
                tagHelpers;
        },

        /**
         * DEV MODE → write file physically
         */
        configureServer(server) {
            const devFilePath = path.resolve(process.cwd(), "public/dist/agnostic-vite-runtime.js");

            // Ensure folder exists
            fs.mkdirSync(path.dirname(devFilePath), { recursive: true });

            // Write runtime file
            fs.writeFileSync(devFilePath, runtimeContent, "utf-8");

            console.log("[agnostic-vite] Wrote dev runtime:", devFilePath);
        },

        /**
         * BUILD MODE → emit as bundle asset
         */
        generateBundle() {
            this.emitFile({
                type: "asset",
                fileName: "agnostic-vite-runtime.js",
                source: runtimeContent,
            });
        },
    };
};