import { Plugin, ResolvedConfig } from "vite"
import fs from "fs"
import path from "path"
import * as process from "process"

type AgnosticViteArgs = {
  assetsDir: string
}

const agnosticVite = (args: AgnosticViteArgs): Plugin => {
  let viteConfig: ResolvedConfig
  let viteRuntimeScript = ""

  return {
    name: "agnostic-vite",

    configResolved (config: ResolvedConfig) {
      viteConfig = config

      const isDevHelper = `
 const IS_DEV = ${viteConfig.command === "serve"};

 const VITE_HOST = ${viteConfig.server?.host ? JSON.stringify(`http://${viteConfig.server.host}:${viteConfig.server.port}`) : "http://localhost:5173"};

 const OUT_DIR = "${viteConfig.build.outDir.split("/")[1] || viteConfig.build.outDir}";

 const BASE_ASSETS_DIR = ${JSON.stringify(args.assetsDir) || "public"}

 let _MANIFEST = null;
`

      const manifestHelper = `
// Helper to fetch text content of a file
async function fetchText(file) {
    return await (await fetch(file)).text();
}

// Loads the manifest file, uses a cached version if available
async function loadManifest() {
    if (_MANIFEST) {
        return _MANIFEST;
    }
    const url = OUT_DIR + "/" + "manifest.json";
    _MANIFEST = JSON.parse(await fetchText(url));
    return _MANIFEST;
}

async function getAsset(entry) {
    const manifest = await loadManifest();
    return manifest[BASE_ASSETS_DIR + "/" + entry] || null;
}
`

      const tagHelpers = `
// Helper to create and append a CSS link tag
function injectLinkTag(href, isProd = true) {
    const head = document.head || document.getElementsByTagName('head')[0];
    if (!head) return;

    const link = document.createElement("link");
    link.rel = "stylesheet";

    if (isProd) {
        link.href = OUT_DIR + "/" + href;
    } else {
        link.href = VITE_HOST + "/" + href;
    }

    head.appendChild(link);
}

async function viteAsset(entry) {
    const headElement = document.head || document.getElementsByTagName('head')[0];
    const bodyElement = document.body || document.getElementsByTagName('body')[0];

    if (!headElement && !bodyElement) {
        console.error("Invalid HTML DOM, missing head or body elements.");
        return;
    }

    const isJS = entry.endsWith(".js");
    const isCSS = entry.endsWith(".css");

    if (!isJS && !isCSS) {
        console.warn('Unsupported asset type for entry:', entry);
        return;
    }

    if (IS_DEV) {
        if (isJS) {
            const script = document.createElement("script");
            script.type = "module";
            script.crossOrigin = true;
            script.src = VITE_HOST + "/" + entry;
            if(bodyElement) bodyElement.appendChild(script);
        } else if (isCSS) {
            injectLinkTag(entry, false);
        }
        return;
    }

    const asset = await getAsset(entry);
    if (!asset) {
        console.warn('Asset not found in manifest:', entry);
        return;
    }

    if (asset.css) {
        asset.css.forEach(cssFile => {
            injectLinkTag(cssFile);
        });
    } 
    if (asset.file && asset.file.endsWith(".css")) {
        injectLinkTag(asset.file);
    }

    if (isJS) {
        const script = document.createElement("script");
        script.type = "module";
        script.src = OUT_DIR + "/" + asset.file;
        if(bodyElement) bodyElement.appendChild(script);
    }
}

if (typeof window !== "undefined") {
    window.viteAsset = viteAsset;
}
`

      viteRuntimeScript =
        "// Auto-generated by agnostic-vite plugin\n\n" +
        isDevHelper +
        manifestHelper +
        tagHelpers
    },

    /**
     * DEV MODE → write file physically
     */
    configureServer (server) {
      const devFilePath = path.resolve(process.cwd(), `${viteConfig.build.outDir}/agnostic-vite-runtime.js`)

      // Ensure folder exists
      fs.mkdirSync(path.dirname(devFilePath), { recursive: true })

      // Write runtime file
      fs.writeFileSync(devFilePath, viteRuntimeScript, "utf-8")

      console.info("[agnostic-vite] Wrote dev runtime:", devFilePath)
    },

    /**
     * BUILD MODE → emit as bundle asset
     */
    generateBundle () {
      this.emitFile({
        type: "asset",
        fileName: "agnostic-vite-runtime.js",
        source: viteRuntimeScript,
      })
    },
  }
}

export default agnosticVite